#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6448481123                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Lemon Schedules                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Lemon Schedules makes educational scheduling quick and easy.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Blue Mountain Studios, LLC                              
your_link                                 : https://www.bluemountainstudios.net                     
your_city                                 : Birmingham, AL                                
email_address                             : support@lemonschedules.com
facebook_username                         :                                           
instagram_username                        : ebaehr
twitter_username                          : ebaehr
github_username                           : emilbaehr
youtube_username                          :
mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Simple Scheduling
    description                           : Use Lemon Schedules your way! Enter data easily using a spreadsheet or directly enter it into the app. When you’re done, export your schedule to your calendar app or to a spreadsheet. 
    fontawesome_icon_name                 : calendar
    
  - title                                 : In-App Schedule Editing
    description                           : Our computer generated schedules are great, but you can make it better. Use the in-app editor to optimize your schedule to your students' needs. 
    fontawesome_icon_name                 : pen

  - title                                 : Focus Areas
    description                           : Each of your students are unique. Use Focus Areas to intelligently group or separate your students by goal area, needs, standards, or even personality traits. 
    fontawesome_icon_name                 : fa-solid fa-magnifying-glass

  - title                                 : Schedule Auditing
    description                           : We’ll double check your schedule to make sure your schedule meets all of your requirements.
    fontawesome_icon_name                 : stethoscope

  - title                                 : Privacy First
    description                           : Lemon Schedules takes privacy seriously. All personal, student, and scheduling data you enter is stored on your device and never uploaded or sold. We’re fully FERPA and HIPAA compliant. 
    fontawesome_icon_name                 : lock

bottom_paragraph                          : Lemon Schedules is a family operation. The concept for Lemon Schedules came from brainstorming solutions to real life challenges at the dinner table. Thanks for supporting our small business and joining our family!

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.9
topbar_title_color                        : "#ffffff"

cover_image                               : assets/yellow_bg.png                
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#4D9B6F"

app_title_color                           : "#000000"
app_price_color                           : "#ffffff"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#4D9B6F"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
